services:
  node:
    build:
      context: ./Front
    ports:
      - "5000:5000"
    container_name: frontend
    volumes:
      - ./Front:/app
    tty: true
    stdin_open: true
    command: /bin/sh

  php-fpm:
    container_name: php-fpm
    build:
      context: ./Backend
    volumes:
      - ./Backend:/var/www/backend
    depends_on:
      - postgresql
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Front:/var/www/frontend
      - ./Backend:/var/www/backend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - node

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:4.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  postgresql:
    container_name: postgres
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_map

  adminer:
    container_name: adminer
    image: adminer:5-standalone
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - postgresql
