services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./Backend
      network: host
    volumes:
      - ./Backend:/var/www/backend
    depends_on:
      - postgresql
      - rabbitmq
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./Front:/var/www/frontend
      - ./Backend:/var/www/backend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_PORT_ADMIN}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network

  postgresql:
    container_name: postgres
    image: postgres:17.5-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer:5-standalone
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgresql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
