services:
  node:
    build:
      context: ./Front
    ports:
      - "5000:5000"
    container_name: frontend
    volumes:
      - ./Front:/app

  php-fpm:
    container_name: php-fpm
    build:
      context: ./Backend
    volumes:
      - ./Backend:/var/www/backend

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Front:/var/www/frontend
      - ./Backend:/var/www/backend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:4.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
