services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./Backend
      network: host
    volumes:
      - ./Backend:/var/www/backend
    depends_on:
      - postgresql
      - rabbitmq
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Front:/var/www/frontend
      - ./Backend:/var/www/backend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - node
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  postgresql:
    container_name: postgres
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_map
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer:5-standalone
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - postgresql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
